---
- name: Include OS specific variables.
  include_vars: "{{ ansible_os_family | lower }}.yml"

- name: Update cache on Debian based hosts
  apt:
    update_cache: true
  when: ansible_facts['os_family'] == "Debian"
  changed_when: false

- name: Install required packages
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ required_packages }}"

- name: Transfer template file to the remote machines
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644

- name: Ensure firewalld is started and enabled
  service:
    name: firewalld
    state: started
    enabled: true
  when: (firewalld_enabled | bool)

- name: Set timezone to {{ timezone }}
  timezone:
    name: "{{ timezone }}"
